apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
  labels:
    app: rs-test
spec:
  replicas: 2 # Número de réplicas que quieres ejecutar
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: contenedor1
        image: python:3.6-alpine # Imagen de Docker del contenedor
        command: ['sh', '-c', 'python -m http.server 8081']
      - name: contenedor2
        image: python:3.6-alpine # Imagen de Docker del contenedor
        command: ['sh', '-c', 'python -m http.server 8082']
